name: Build project
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Validate
        uses: pre-commit/action@v3.0.0

      - name: Run Apache Superset
        timeout-minutes: 10
        run: docker compose up -d --wait

      - name: Stop containers
        if: always()
        timeout-minutes: 5
        continue-on-error: true
        run: docker compose down -v
